version: '3.7'

services:

  db:
    image: postgres
    container_name: kotw_db
    restart: always
    env_file:
    - ./.env
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  adminer:
    image: adminer
    container_name: kotw_adminer
    restart: always
    ports:
    - "8081:8080"
    depends_on:
    - db

  django:
    build:
      context: ./docker/django
      dockerfile: ./Dockerfile
    container_name: kotw_django
    restart: always
    working_dir: /app/
    ports:
    - "8080:8000"
    env_file:
    - ./.env
    volumes:
    - ./src/:/app/
    depends_on:
    - db
    command: ["bash", "/watch.sh"]